# docker-compose.prod.yml

services:
  backend_gis:
    # Use a standard environment variable that Docker Compose understands.
    # This variable will be set by our deployment script.
    image: ${PROD_IMAGE_NAME}
    container_name: uxo_system_prod_container
    
    # Starts Gunicorn to serve your Django app.
    command: gunicorn uxo_backend.wsgi:application --bind 0.0.0.0:8000

    # NOTE: The development volume for code is removed.
    # The code is baked into the Docker image.
    volumes:
      # Only need a volume for user-uploaded media files now.
      - ./media:/UXO_system_dockerized_gis/media

    ports:
      # Mapping port 80 (standard HTTP) on the host to port 8000 in the container.
      - "80:8000"
    
    env_file:
      - .env.gis
