# docker-compose.gis.yml - For Azure PostGIS environment
services:
  backend_gis:
    build:
      context: .
      dockerfile: Dockerfile.gis # MODIFIED: Explicitly point to Dockerfile.gis
    container_name: uxo_system_container_azure_gis
    command: >
      sh -c "echo 'INFO: Attempting to connect to Azure PostgreSQL...' &&
             python manage.py makemigrations uxo_records &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/UXO_system_dockerized_gis
    ports:
      - "8001:8000" # Host port 8001 maps to container port 8000
    env_file:
      - .env.gis
    # No 'depends_on' for a database service, as the DB is external.

# No 'db_gis' service or 'db_data_gis' volume needed as DB is on Azure.