services:
  backend_gis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uxo_system_container_azure_gis
    command: >
      sh -c "echo 'INFO: Applying database migrations...' &&
             python manage.py migrate &&
             echo 'INFO: Starting development server...' &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/UXO_system_dockerized_gis
    ports:
      - "8001:8000"
    env_file:
      - .env.gis