# reports/models.py

from django.db import models
from django.contrib.gis.db import models as gis_models


class HotZone(models.Model):
    """
    Represents a calculated risk "hot zone" polygon, generated by
    clustering high-risk UXORecord points.

    This table is populated and managed by the 'generate_hotzones'
    management command.
    """

    geometry = gis_models.PolygonField(
        help_text="The polygon shape of the calculated hot zone."
    )
    record_count = models.IntegerField(
        help_text="Number of UXO records within this hot zone."
    )
    avg_danger_score = models.FloatField(
        help_text="The average danger score of all records in this zone."
    )

    class Meta:
        verbose_name = "Risk Hot Zone"
        verbose_name_plural = "Risk Hot Zones"

    def __str__(self):
        return f"Hot Zone {self.id} (Records: {self.record_count}, Avg Score: {self.avg_danger_score:.2f})"
